
package ru.atc.er.soap2restadapterservice.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SendBadResponse", targetNamespace = "http://soap2RestAdapterService.er.atc.ru/ws")
public class SendBadResponse_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SendBadResponse faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SendBadResponse_Exception(String message, SendBadResponse faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SendBadResponse_Exception(String message, SendBadResponse faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.atc.er.soap2restadapterservice.ws.SendBadResponse
     */
    public SendBadResponse getFaultInfo() {
        return faultInfo;
    }

}
