
package ru.atc.er.soap2restadapterservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Soap2RestAdapterServiceInterface", targetNamespace = "http://soap2RestAdapterService.er.atc.ru/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Soap2RestAdapterServiceInterface {


    /**
     * 
     * @param sendRequest
     * @return
     *     returns ru.atc.er.soap2restadapterservice.ws.SendResponse
     * @throws SendBadResponse_Exception
     */
    @WebMethod(operationName = "Send", action = "SendElectronicRegistry")
    @WebResult(name = "SendResponse", targetNamespace = "http://soap2RestAdapterService.er.atc.ru/ws", partName = "SendResponse")
    public SendResponse send(
        @WebParam(name = "SendRequest", targetNamespace = "http://soap2RestAdapterService.er.atc.ru/ws", partName = "SendRequest")
        Send sendRequest)
        throws SendBadResponse_Exception
    ;

}
